# Generated by Django 2.2.11 on 2020-03-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_as_aqa"),
        ("users", "0002_auto_20200320_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_home",
                to="home.HomePage",
            ),
        ),
    ]
