# Generated by Django 2.2.11 on 2020-03-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_testing"),
    ]

    operations = [
        migrations.CreateModel(
            name="As",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asd", models.BigIntegerField()),
            ],
        ),
    ]
