# Generated by Django 2.2.11 on 2020-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='as',
            name='aqa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
